/*-------------------------------------------------------------------------
 *
 * pg_stash_advice.c
 *	  Apply plan advice automatically, without SQL modifications.
 *
 * This module allows plan advice strings (as used and generated by
 * pg_plan_advice) to be "stashed" in dynamic shared memory and, from
 * there, automatically be applied to queries as they are planned.
 * You can create any number of advice stashes, each of which is
 * identified by a human-readable, ASCII name, and each of them is
 * essentially a query ID -> advice_string mapping.
 *
 * Copyright (c) 2016-2026, PostgreSQL Global Development Group
 *
 *	  contrib/pg_stash_advice/pg_stash_advice.c
 *
 *-------------------------------------------------------------------------
 */
#include "postgres.h"

#include "common/hashfn.h"
#include "common/string.h"
#include "fmgr.h"
#include "funcapi.h"
#include "lib/dshash.h"
#include "nodes/queryjumble.h"
#include "pg_plan_advice.h"
#include "storage/dsm_registry.h"
#include "storage/lwlock.h"
#include "utils/builtins.h"
#include "utils/guc.h"
#include "utils/memutils.h"

PG_MODULE_MAGIC;

PG_FUNCTION_INFO_V1(pg_create_advice_stash);
PG_FUNCTION_INFO_V1(pg_drop_advice_stash);
PG_FUNCTION_INFO_V1(pg_get_advice_stash_contents);
PG_FUNCTION_INFO_V1(pg_get_advice_stashes);
PG_FUNCTION_INFO_V1(pg_set_stashed_advice);

typedef struct pgsa_shared_state
{
	LWLock		lock;
	int			dsa_tranche;
	int			stash_tranche;
	int			entry_tranche;
	int			next_stash_id;
	dsa_handle	area;
	dshash_table_handle stash_hash;
	dshash_table_handle entry_hash;
} pgsa_shared_state;

typedef struct pgsa_stash
{
	char		name[NAMEDATALEN];
	int			pgsa_stash_id;
} pgsa_stash;

typedef struct pgsa_entry_key
{
	int			pgsa_stash_id;
	int64		queryId;
} pgsa_entry_key;

typedef struct pgsa_entry
{
	pgsa_entry_key key;
	dsa_pointer advice_string;
} pgsa_entry;

typedef struct pgsa_stash_count
{
	uint32		status;
	int			pgsa_stash_id;
	int64		num_entries;
} pgsa_stash_count;

#define SH_PREFIX pgsa_stash_count_table
#define SH_ELEMENT_TYPE pgsa_stash_count
#define SH_KEY_TYPE int
#define SH_KEY pgsa_stash_id
#define SH_HASH_KEY(tb, key) murmurhash32((uint32) key)
#define SH_EQUAL(tb, a, b) (a == b)
#define SH_SCOPE static inline
#define SH_DEFINE
#define SH_DECLARE
#include "lib/simplehash.h"

typedef struct pgsa_stash_name
{
	uint32		status;
	int			pgsa_stash_id;
	char	   *name;
} pgsa_stash_name;

#define SH_PREFIX pgsa_stash_name_table
#define SH_ELEMENT_TYPE pgsa_stash_name
#define SH_KEY_TYPE int
#define SH_KEY pgsa_stash_id
#define SH_HASH_KEY(tb, key) murmurhash32((uint32) key)
#define SH_EQUAL(tb, a, b) (a == b)
#define SH_SCOPE static inline
#define SH_DEFINE
#define SH_DECLARE
#include "lib/simplehash.h"

/* Shared memory pointers */
static pgsa_shared_state *pgsa_state;
static dsa_area *pgsa_dsa_area;
static dshash_table *pgsa_stash_dshash;
static dshash_table *pgsa_entry_dshash;

/* Shared memory hash table parameters */
static dshash_parameters pgsa_stash_dshash_parameters = {
	NAMEDATALEN,
	sizeof(pgsa_stash),
	dshash_strcmp,
	dshash_strhash,
	dshash_strcpy,
	LWTRANCHE_INVALID			/* gets set at runtime */
};

static dshash_parameters pgsa_entry_dshash_parameters = {
	sizeof(pgsa_entry_key),
	sizeof(pgsa_entry),
	dshash_memcmp,
	dshash_memhash,
	dshash_memcpy,
	LWTRANCHE_INVALID			/* gets set at runtime */
};

/* GUC variable */
static char *pg_stash_advice_stash_name = "";

/* Other global variables */
static MemoryContext pg_stash_advice_mcxt;

/* Function prototypes */
static char *pgsa_advisor(PlannerGlobal *glob,
						  Query *parse,
						  const char *query_string,
						  int cursorOptions,
						  ExplainState *es);
static void pgsa_attach(void);
static void pgsa_check_stash_name(char *stash_name);
static bool pgsa_check_stash_name_guc(char **newval, void **extra,
									  GucSource source);
static void pgsa_clear_advice_string(char *stash_name, int64 queryId);
static void pgsa_create_stash(char *stash_name);
static void pgsa_drop_stash(char *stash_name);
static void pgsa_init_shared_state(void *ptr, void *arg);
static int	pgsa_lookup_stash_id(char *stash_name);
static void pgsa_set_advice_string(char *stash_name, int64 queryId,
								   char *advice_string);

/*
 * Initialize this module.
 */
void
_PG_init(void)
{
	void		(*add_advisor_fn) (pg_plan_advice_advisor_hook hook);

	/* If compute_query_id = 'auto', we would like query IDs. */
	EnableQueryId();

	/* Define our GUCs. */
	DefineCustomStringVariable("pg_stash_advice.stash_name",
							   "Name of the advice stash to be used in this session.",
							   NULL,
							   &pg_stash_advice_stash_name,
							   "",
							   PGC_USERSET,
							   0,
							   pgsa_check_stash_name_guc,
							   NULL,
							   NULL);

	MarkGUCPrefixReserved("pg_stash_advice");

	/* Tell pg_plan_advice that we want to provide advice strings. */
	add_advisor_fn =
		load_external_function("pg_plan_advice", "pg_plan_advice_add_advisor",
							   true, NULL);
	(*add_advisor_fn) (pgsa_advisor);
}

/*
 * SQL-callable function to create an advice stash
 */
Datum
pg_create_advice_stash(PG_FUNCTION_ARGS)
{
	char	   *stash_name = text_to_cstring(PG_GETARG_TEXT_PP(0));

	pgsa_check_stash_name(stash_name);
	if (unlikely(pgsa_entry_dshash == NULL))
		pgsa_attach();
	LWLockAcquire(&pgsa_state->lock, LW_EXCLUSIVE);
	pgsa_create_stash(stash_name);
	LWLockRelease(&pgsa_state->lock);
	PG_RETURN_VOID();
}

/*
 * SQL-callable function to drop an advice stash
 */
Datum
pg_drop_advice_stash(PG_FUNCTION_ARGS)
{
	char	   *stash_name = text_to_cstring(PG_GETARG_TEXT_PP(0));

	pgsa_check_stash_name(stash_name);
	if (unlikely(pgsa_entry_dshash == NULL))
		pgsa_attach();
	LWLockAcquire(&pgsa_state->lock, LW_EXCLUSIVE);
	pgsa_drop_stash(stash_name);
	LWLockRelease(&pgsa_state->lock);
	PG_RETURN_VOID();
}

/*
 * SQL-callable function to provide a list of advice stashes
 */
Datum
pg_get_advice_stashes(PG_FUNCTION_ARGS)
{
	ReturnSetInfo *rsinfo = (ReturnSetInfo *) fcinfo->resultinfo;
	dshash_seq_status iterator;
	pgsa_entry *entry;
	pgsa_stash *stash;
	pgsa_stash_count_table_hash *chash;

	InitMaterializedSRF(fcinfo, 0);

	/* Attach to dynamic shared memory if not already done. */
	if (unlikely(pgsa_entry_dshash == NULL))
		pgsa_attach();

	/* Tally up the number of entries per stash. */
	chash = pgsa_stash_count_table_create(CurrentMemoryContext, 64, NULL);
	dshash_seq_init(&iterator, pgsa_entry_dshash, true);
	while ((entry = dshash_seq_next(&iterator)) != NULL)
	{
		pgsa_stash_count *c;
		bool		found;

		c = pgsa_stash_count_table_insert(chash,
										  entry->key.pgsa_stash_id,
										  &found);
		if (!found)
			c->num_entries = 1;
		else
			c->num_entries++;
	}
	dshash_seq_term(&iterator);

	/* Emit results. */
	dshash_seq_init(&iterator, pgsa_stash_dshash, true);
	while ((stash = dshash_seq_next(&iterator)) != NULL)
	{
		Datum		values[2];
		bool		nulls[2];
		pgsa_stash_count *c;

		values[0] = CStringGetTextDatum(stash->name);
		nulls[0] = false;

		c = pgsa_stash_count_table_lookup(chash, stash->pgsa_stash_id);
		values[1] = Int64GetDatum(c == NULL ? 0 : c->num_entries);
		nulls[1] = false;

		tuplestore_putvalues(rsinfo->setResult, rsinfo->setDesc, values,
							 nulls);
	}
	dshash_seq_term(&iterator);

	return (Datum) 0;
}

/*
 * SQL-callable function to provide advice stash contents
 */
Datum
pg_get_advice_stash_contents(PG_FUNCTION_ARGS)
{
	ReturnSetInfo *rsinfo = (ReturnSetInfo *) fcinfo->resultinfo;
	dshash_seq_status iterator;
	char	   *stash_name = NULL;
	pgsa_stash_name_table_hash *nhash = NULL;
	int			stash_id = 0;
	pgsa_entry *entry;

	InitMaterializedSRF(fcinfo, 0);

	/* Attach to dynamic shared memory if not already done. */
	if (unlikely(pgsa_entry_dshash == NULL))
		pgsa_attach();

	/* User can pass NULL for all stashes, or the name of a specific stash. */
	if (!PG_ARGISNULL(0))
	{
		stash_name = text_to_cstring(PG_GETARG_TEXT_PP(0));
		pgsa_check_stash_name(stash_name);
		stash_id = pgsa_lookup_stash_id(stash_name);

		/* If the user specified a stash name, it should exist. */
		if (stash_id == 0)
			ereport(ERROR,
					errcode(ERRCODE_INVALID_PARAMETER_VALUE),
					errmsg("advice stash \"%s\" does not exist", stash_name));
	}
	else
	{
		pgsa_stash *stash;

		/*
		 * If we're dumping data about all stashes, we need an ID->name lookup
		 * table.
		 */
		nhash = pgsa_stash_name_table_create(CurrentMemoryContext, 64, NULL);
		dshash_seq_init(&iterator, pgsa_stash_dshash, true);
		while ((stash = dshash_seq_next(&iterator)) != NULL)
		{
			pgsa_stash_name *n;
			bool		found;

			n = pgsa_stash_name_table_insert(nhash,
											 stash->pgsa_stash_id,
											 &found);
			Assert(!found);
			n->name = pstrdup(stash->name);
		}
		dshash_seq_term(&iterator);
	}

	/* Now iterate over all the entries. */
	dshash_seq_init(&iterator, pgsa_entry_dshash, false);
	while ((entry = dshash_seq_next(&iterator)) != NULL)
	{
		Datum		values[3];
		bool		nulls[3];
		char	   *this_stash_name;
		char	   *advice_string;

		/* Skip incomplete entries where the advice string was never set. */
		if (entry->advice_string == InvalidDsaPointer)
			continue;

		if (stash_id != 0)
		{
			/*
			 * We're only dumping data for one particular stash, so skip
			 * entries for any other stash and use the stash name specified by
			 * the user.
			 */
			if (stash_id != entry->key.pgsa_stash_id)
				continue;
			this_stash_name = stash_name;
		}
		else
		{
			pgsa_stash_name *n;

			/*
			 * We're dumping data for all stashes, so look up the correct name
			 * to use in the hash table. If nothing is found, which is
			 * possible due to race conditions, make up a string to use.
			 */
			n = pgsa_stash_name_table_lookup(nhash, entry->key.pgsa_stash_id);
			if (n != NULL)
				this_stash_name = n->name;
			else
				this_stash_name = psprintf("<stash %d>",
										   entry->key.pgsa_stash_id);
		}

		/* Work out tuple values. */
		values[0] = CStringGetTextDatum(this_stash_name);
		nulls[0] = false;
		values[1] = Int64GetDatum(entry->key.queryId);
		nulls[1] = false;
		advice_string = dsa_get_address(pgsa_dsa_area, entry->advice_string);
		values[2] = CStringGetTextDatum(advice_string);
		nulls[2] = false;

		/* Emit the tuple. */
		tuplestore_putvalues(rsinfo->setResult, rsinfo->setDesc, values,
							 nulls);
	}
	dshash_seq_term(&iterator);

	return (Datum) 0;
}

/*
 * SQL-callable function to update an advice stash entry for a particular
 * query ID
 *
 * If the second argument is NULL, we delete any existing advice stash
 * entry; otherwise, we either create an entry or update it with the new
 * advice string.
 */
Datum
pg_set_stashed_advice(PG_FUNCTION_ARGS)
{
	char	   *stash_name;
	int64		queryId;

	if (PG_ARGISNULL(0) || PG_ARGISNULL(1))
		PG_RETURN_NULL();

	/* Get and check advice stash name. */
	stash_name = text_to_cstring(PG_GETARG_TEXT_PP(0));
	pgsa_check_stash_name(stash_name);

	/*
	 * Get and check query ID.
	 *
	 * queryID 0 means no query ID was computed, so reject that.
	 */
	queryId = PG_GETARG_INT64(1);
	if (queryId == 0)
		ereport(ERROR,
				errcode(ERRCODE_INVALID_PARAMETER_VALUE),
				errmsg("cannot set advice string for query ID 0"));

	/* Attach to dynamic shared memory if not already done. */
	if (unlikely(pgsa_entry_dshash == NULL))
		pgsa_attach();

	/* Now call the appropriate function to do the real work. */
	if (PG_ARGISNULL(2))
		pgsa_clear_advice_string(stash_name, queryId);
	else
	{
		char	   *advice_string = text_to_cstring(PG_GETARG_TEXT_PP(2));

		pgsa_set_advice_string(stash_name, queryId, advice_string);
	}

	PG_RETURN_VOID();
}

/*
 * Get the advice string that has been configured for this query, if any,
 * and return it. Otherwise, return NULL.
 */
static char *
pgsa_advisor(PlannerGlobal *glob, Query *parse,
			 const char *query_string, int cursorOptions,
			 ExplainState *es)
{
	pgsa_entry_key key;
	pgsa_entry *entry;
	char	   *advice_string;
	int			stash_id;

	/*
	 * Exit quickly if the stash name is empty or there's no query ID.
	 */
	if (pg_stash_advice_stash_name[0] == '\0' || parse->queryId == 0)
		return NULL;

	/* Attach to dynamic shared memory if not already done. */
	if (unlikely(pgsa_entry_dshash == NULL))
		pgsa_attach();

	/*
	 * Translate pg_stash_advice.stash_name to an integer ID.
	 *
	 * pgsa_check_stash_name_guc() has already validated the advice stash
	 * name, so we don't need to call pgsa_check_stash_name() here.
	 */
	stash_id = pgsa_lookup_stash_id(pg_stash_advice_stash_name);
	if (stash_id == 0)
		return NULL;

	/*
	 * Look up the advice string for the given stash ID + query ID.
	 *
	 * If we find an advice string, we copy it into the current memory
	 * context, presumably short-lived, so that we can release the lock on the
	 * dshash entry. pg_plan_advice only needs the value to remain allocated
	 * long enough for it to be parsed, so this should be good enough.
	 */
	memset(&key, 0, sizeof(pgsa_entry_key));
	key.pgsa_stash_id = stash_id;
	key.queryId = parse->queryId;
	entry = dshash_find(pgsa_entry_dshash, &key, true);
	if (entry == NULL)
		return NULL;
	if (entry->advice_string == InvalidDsaPointer)
		advice_string = NULL;
	else
		advice_string = pstrdup(dsa_get_address(pgsa_dsa_area,
												entry->advice_string));
	dshash_release_lock(pgsa_entry_dshash, entry);

	/* If we found an advice string, emit a debug message. */
	if (advice_string != NULL)
		elog(DEBUG2, "supplying automatic advice for stash \"%s\", query ID %" PRId64 ": %s",
			 pg_stash_advice_stash_name, key.queryId, advice_string);

	return advice_string;
}

/*
 * Attach to various structures in dynamic shared memory.
 *
 * This function is designed to be resilient against errors. That is, if it
 * fails partway through, it should be possible to call it again, repeat no
 * work already completed, and potentially succeed or at least get further if
 * whatever caused the previous failure has been corrected.
 */
static void
pgsa_attach(void)
{
	bool		found;
	MemoryContext oldcontext;

	/*
	 * Create a memory context to make sure that any control structures
	 * allocated in local memory are sufficiently persistent.
	 */
	if (pg_stash_advice_mcxt == NULL)
		pg_stash_advice_mcxt = AllocSetContextCreate(TopMemoryContext,
													 "pg_stash_advice",
													 ALLOCSET_DEFAULT_SIZES);
	oldcontext = MemoryContextSwitchTo(pg_stash_advice_mcxt);

	/* Attach to the fixed-size state object if not already done. */
	if (pgsa_state == NULL)
		pgsa_state = GetNamedDSMSegment("pg_stash_advice",
										sizeof(pgsa_shared_state),
										pgsa_init_shared_state,
										&found, NULL);

	/* Attach to the DSA area if not already done. */
	if (pgsa_dsa_area == NULL)
	{
		dsa_handle	area_handle;

		LWLockAcquire(&pgsa_state->lock, LW_EXCLUSIVE);
		area_handle = pgsa_state->area;
		if (area_handle == DSA_HANDLE_INVALID)
		{
			pgsa_dsa_area = dsa_create(pgsa_state->dsa_tranche);
			dsa_pin(pgsa_dsa_area);
			pgsa_state->area = dsa_get_handle(pgsa_dsa_area);
			LWLockRelease(&pgsa_state->lock);
		}
		else
		{
			LWLockRelease(&pgsa_state->lock);
			pgsa_dsa_area = dsa_attach(area_handle);
		}
		dsa_pin_mapping(pgsa_dsa_area);
	}

	/* Attach to the stash_name->stash_id hash table if not already done. */
	if (pgsa_stash_dshash == NULL)
	{
		dshash_table_handle stash_handle;

		LWLockAcquire(&pgsa_state->lock, LW_EXCLUSIVE);
		pgsa_stash_dshash_parameters.tranche_id = pgsa_state->stash_tranche;
		stash_handle = pgsa_state->stash_hash;
		if (stash_handle == DSHASH_HANDLE_INVALID)
		{
			pgsa_stash_dshash = dshash_create(pgsa_dsa_area,
											  &pgsa_stash_dshash_parameters,
											  NULL);
			pgsa_state->stash_hash =
				dshash_get_hash_table_handle(pgsa_stash_dshash);
			LWLockRelease(&pgsa_state->lock);
		}
		else
		{
			LWLockRelease(&pgsa_state->lock);
			pgsa_stash_dshash = dshash_attach(pgsa_dsa_area,
											  &pgsa_stash_dshash_parameters,
											  stash_handle, NULL);
		}
	}

	/* Attach to the entry hash table if not already done. */
	if (pgsa_entry_dshash == NULL)
	{
		dshash_table_handle entry_handle;

		LWLockAcquire(&pgsa_state->lock, LW_EXCLUSIVE);
		pgsa_entry_dshash_parameters.tranche_id = pgsa_state->entry_tranche;
		entry_handle = pgsa_state->entry_hash;
		if (entry_handle == DSHASH_HANDLE_INVALID)
		{
			pgsa_entry_dshash = dshash_create(pgsa_dsa_area,
											  &pgsa_entry_dshash_parameters,
											  NULL);
			pgsa_state->entry_hash =
				dshash_get_hash_table_handle(pgsa_entry_dshash);
			LWLockRelease(&pgsa_state->lock);
		}
		else
		{
			LWLockRelease(&pgsa_state->lock);
			pgsa_entry_dshash = dshash_attach(pgsa_dsa_area,
											  &pgsa_entry_dshash_parameters,
											  entry_handle, NULL);
		}
	}

	/* Restore previous memory context. */
	MemoryContextSwitchTo(oldcontext);
}

/*
 * Check whether an advice stash name is legal, and signal an error if not.
 *
 * Keep this in sync with pgsa_check_stash_name_guc, below.
 */
static void
pgsa_check_stash_name(char *stash_name)
{
	/* Reject empty advice stash name. */
	if (stash_name[0] == '\0')
		ereport(ERROR,
				errcode(ERRCODE_INVALID_PARAMETER_VALUE),
				errmsg("advice stash name may not be zero length"));

	/* Reject overlong advice stash names. */
	if (strlen(stash_name) + 1 > NAMEDATALEN)
		ereport(ERROR,
				errcode(ERRCODE_INVALID_PARAMETER_VALUE),
				errmsg("advice stash names may not be longer than %d bytes",
					   NAMEDATALEN - 1));

	/*
	 * Reject non-ASCII advice stash names, since advice stashes are visible
	 * across all databases and the encodings of those databases might differ.
	 */
	if (!pg_is_ascii(stash_name))
		ereport(ERROR,
				errcode(ERRCODE_INVALID_PARAMETER_VALUE),
				errmsg("advice stash name must not contain non-ASCII characters"));
}

/*
 * As above, but for the GUC check_hook. We allow the empty string here,
 * though, as equivalent to disabling the feature.
 */
static bool
pgsa_check_stash_name_guc(char **newval, void **extra, GucSource source)
{
	char	   *stash_name = *newval;

	/* Reject overlong advice stash names. */
	if (strlen(stash_name) + 1 > NAMEDATALEN)
	{
		GUC_check_errcode(ERRCODE_INVALID_PARAMETER_VALUE);
		GUC_check_errdetail("advice stash names may not be longer than %d bytes",
							NAMEDATALEN - 1);
		return false;
	}

	/*
	 * Reject non-ASCII advice stash names, since advice stashes are visible
	 * across all databases and the encodings of those databases might differ.
	 */
	if (!pg_is_ascii(stash_name))
	{
		GUC_check_errcode(ERRCODE_INVALID_PARAMETER_VALUE);
		GUC_check_errdetail("advice stash name must not contain non-ASCII characters");
		return false;
	}

	return true;
}

/*
 * Create an advice stash.
 */
static void
pgsa_create_stash(char *stash_name)
{
	pgsa_stash *stash;
	bool		found;

	Assert(LWLockHeldByMeInMode(&pgsa_state->lock, LW_EXCLUSIVE));

	/* Create a stash with this name, unless one already exists. */
	stash = dshash_find_or_insert(pgsa_stash_dshash, stash_name, &found);
	if (found)
		ereport(ERROR,
				errcode(ERRCODE_INVALID_PARAMETER_VALUE),
				errmsg("advice stash \"%s\" already exists", stash_name));
	stash->pgsa_stash_id = pgsa_state->next_stash_id++;
	dshash_release_lock(pgsa_stash_dshash, stash);
}

/*
 * Remove any stored advice string for the given advice stash and query ID.
 */
static void
pgsa_clear_advice_string(char *stash_name, int64 queryId)
{
	pgsa_entry *entry;
	pgsa_entry_key key;
	int			stash_id;
	dsa_pointer old_dp;

	/* Translate the stash name to an integer ID. */
	if ((stash_id = pgsa_lookup_stash_id(stash_name)) == 0)
		ereport(ERROR,
				errcode(ERRCODE_INVALID_PARAMETER_VALUE),
				errmsg("advice stash \"%s\" does not exist", stash_name));

	/*
	 * Look for an existing entry, and free it. But, be sure to save the
	 * pointer to the associated advice string, if any.
	 */
	memset(&key, 0, sizeof(pgsa_entry_key));
	key.pgsa_stash_id = stash_id;
	key.queryId = queryId;
	entry = dshash_find(pgsa_entry_dshash, &key, true);
	if (entry == NULL)
		old_dp = InvalidDsaPointer;
	else
	{
		old_dp = entry->advice_string;
		dshash_delete_entry(pgsa_entry_dshash, entry);
	}

	/* Now we free the advice string as well, if there was one. */
	if (old_dp != InvalidDsaPointer)
		dsa_free(pgsa_dsa_area, old_dp);
}

/*
 * Drop an advice stash.
 */
static void
pgsa_drop_stash(char *stash_name)
{
	pgsa_entry *entry;
	pgsa_stash *stash;
	dshash_seq_status iterator;
	int			stash_id;

	Assert(LWLockHeldByMeInMode(&pgsa_state->lock, LW_EXCLUSIVE));

	/* Remove the entry for this advice stash. */
	stash = dshash_find(pgsa_stash_dshash, stash_name, true);
	if (stash == NULL)
		ereport(ERROR,
				errcode(ERRCODE_INVALID_PARAMETER_VALUE),
				errmsg("advice stash \"%s\" does not exist", stash_name));
	stash_id = stash->pgsa_stash_id;
	dshash_delete_entry(pgsa_stash_dshash, stash);

	/*
	 * It should now be impossible for any new entries to be added for the
	 * advice stash we just deleted. Go through and clean out all the existing
	 * ones.
	 */
	dshash_seq_init(&iterator, pgsa_entry_dshash, true);
	while ((entry = dshash_seq_next(&iterator)) != NULL)
	{
		if (stash_id == entry->key.pgsa_stash_id)
		{
			if (entry->advice_string != InvalidDsaPointer)
				dsa_free(pgsa_dsa_area, entry->advice_string);
			dshash_delete_current(&iterator);
		}
	}
	dshash_seq_term(&iterator);
}

/*
 * Initialize shared state when first created.
 */
static void
pgsa_init_shared_state(void *ptr, void *arg)
{
	pgsa_shared_state *state = (pgsa_shared_state *) ptr;

	LWLockInitialize(&state->lock,
					 LWLockNewTrancheId("pg_stash_advice_lock"));
	state->dsa_tranche = LWLockNewTrancheId("pg_stash_advice_dsa");
	state->stash_tranche = LWLockNewTrancheId("pg_stash_advice_stash");
	state->entry_tranche = LWLockNewTrancheId("pg_stash_advice_entry");
	state->next_stash_id = 1;
	state->area = DSA_HANDLE_INVALID;
	state->stash_hash = DSHASH_HANDLE_INVALID;
	state->entry_hash = DSHASH_HANDLE_INVALID;
}

/*
 * Look up the integer ID that corresponds to the given stash name.
 *
 * Returns 0 if no such stash exists.
 */
static int
pgsa_lookup_stash_id(char *stash_name)
{
	pgsa_stash *stash;
	int			stash_id;

	/* Search the shared hash table. */
	stash = dshash_find(pgsa_stash_dshash, stash_name, false);
	if (stash == NULL)
		return 0;
	stash_id = stash->pgsa_stash_id;
	dshash_release_lock(pgsa_stash_dshash, stash);

	return stash_id;
}

/*
 * Store a new or updated advice string for the given advice stash and query ID.
 */
static void
pgsa_set_advice_string(char *stash_name, int64 queryId, char *advice_string)
{
	pgsa_entry *entry;
	bool		found;
	pgsa_entry_key key;
	int			stash_id;
	dsa_pointer new_dp;
	dsa_pointer old_dp;

	/* Translate the stash name to an integer ID. */
restart:
	if ((stash_id = pgsa_lookup_stash_id(stash_name)) == 0)
		ereport(ERROR,
				errcode(ERRCODE_INVALID_PARAMETER_VALUE),
				errmsg("advice stash \"%s\" does not exist", stash_name));

	/* Make sure that an entry exists. */
	memset(&key, 0, sizeof(pgsa_entry_key));
	key.pgsa_stash_id = stash_id;
	key.queryId = queryId;
	entry = dshash_find_or_insert(pgsa_entry_dshash, &key, &found);
	if (!found)
		entry->advice_string = InvalidDsaPointer;
	dshash_release_lock(pgsa_entry_dshash, entry);

	/*
	 * Copy the advice string into dynamic shared memory.
	 *
	 * If we fail after this point, we'll have a server-lifespan memory leak.
	 * We assume that, having created the entry above, we'll be able to find
	 * it again without an error.
	 */
	new_dp = dsa_allocate(pgsa_dsa_area, strlen(advice_string) + 1);
	strcpy(dsa_get_address(pgsa_dsa_area, new_dp), advice_string);

	/*
	 * Refind the entry and swap the new pointer into place.
	 *
	 * If the entry has been deleted since we found or created it above, free
	 * memory and retry from the top.
	 */
	entry = dshash_find(pgsa_entry_dshash, &key, true);
	if (entry == NULL)
	{
		dsa_free(pgsa_dsa_area, new_dp);
		goto restart;
	}
	old_dp = entry->advice_string;
	entry->advice_string = new_dp;
	dshash_release_lock(pgsa_entry_dshash, entry);

	/* If we replaced an old advice string, free it. */
	if (old_dp != InvalidDsaPointer)
		dsa_free(pgsa_dsa_area, old_dp);
}
